### ISSUE TITLE
Scheduling Add-on?

### ISSUE THREAD

**Issue by ashfurrow** [KrauseFx/mood#4]
Hey, just curious how you automate the tasks for `rake morning` etc? Do you use a Heroku Add-on? Or have a server somewhere?

**Comment by ashfurrow** [comment]
Nevermind! Figured out the Heroku-provided scheduler add-on let's you specify time of day, didn't know it could do that. Thanks!

**Comment by KrauseFx** [comment]
Yeah, that's what I use. I'll update the README to mention it 👍
