### ISSUE TITLE
Porting to Google Script

### ISSUE THREAD

**Issue by NdrsAM** [KrauseFx/mood#7]
I am interested in using the project to another service, hopefully free, for personal use. Heroku seems to be a great solution but it is limited to restrictions such as Dynos down and not using Webhooks seem to be an issue. 

The main targets could be:
1- Porting to a service such as GoogleScript
2- Rewriting the time triggering for the three request each day.
3- Plotting or reporting section.

Do you think if could be done based on this project?

**Comment by KrauseFx** [comment]
Hey, sounds like a good idea, however I'll keep this project, as well as my mood data on Heroku, as it works perfectly fine for what I need it for. Feel free to build it using Google Script, as a separate repo 👍 I'm happy to link to it also once it's done

**Comment by KrauseFx** [comment]
Closing this for now, as I don't plan on working this, feel free to submit a PR if you want this 👍 :)
