### ISSUE TITLE
Request: Instructions to start running the server locally

### ISSUE THREAD

**Issue by RaghavMangrola** [KrauseFx/mood#9]
I wanted to start up the server locally but I'm very unfamiliar with ruby, I suggest adding a Makefile with  any commands necessary to get started locally.

**Comment by ashfurrow** [comment]
Sure, I get that it's hard to get up to speed with a few framework. But it's also important to learn the conventions of Ruby, and in this case, I can point you to the Procfile:

https://github.com/KrauseFx/mood/blob/db0c250fe07bccb4c185e82ffa97f6f2c2fee22f/Procfile

This is used by Heroku to launch your app; you can use [foreman](https://github.com/ddollar/foreman) locally to run the app with `foreman start`.

**Comment by KrauseFx** [comment]
Closing this now 👍

**Comment by KrauseFx** [comment]
Thanks Ash
